#Base on tutorial: https://flutter.dev/docs/development/accessibility-and-localization/internationalization
arb-dir: lib/l10n
template-arb-file: intl_pt.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated.txt